// Method signature fix
//
// When writing Jimple, Soot may create method signatures
// A.m() even though m() is defined in some supertype S of A. This
// creates mismatches between Doop and Jimple identifiers ("S.m" vs. "A.m").

.decl JimpleHack(?subMethodSig:symbol, ?origMethodSig:symbol, ?params:symbol)
.output JimpleHack

JimpleHack(?subMethodSig, ?superMethodSig, ?params) :-
	Method_DeclaringType(?method, ?superType),
	Method_SimpleName(?method, ?simplename),
	Method_Params(?method, ?params),
	SubtypeOf(?subType, ?superType),
	?subType != ?superType,
	!isNullType(?subType),
	?simplename != "<clinit>", ?simplename != "<init>",
	?subMethodSig = cat(?subType, cat(".", ?simplename)),
	?superMethodSig = cat(?superType, cat(".", ?simplename)).