/**
 * A class ?a is a direct subclass of class ?c
 */
.decl DirectSubclass(?a:Type, ?c:Type)

/**
 * A class ?a is a subclass of class ?c
 *
 * NOTE: the ordering might be unnatural, so pay attention when you use this
 * predicate.
 */
.decl Subclass(?c:Type, ?a:Type)

/**
 * A class ?a is a superclass of class ?c
 *
 * NOTE: The ordering might be unnatural, so pay attention when you use this
 * predicate.
 */
.decl Superclass(?c:Type, ?a:Type)
