#! /bin/bash

function gen-text-options()
{
	echo -e "option,delimiter,\"\t\""
	echo "option,hasColumnNames,false"
}

function gen-csv-options()
{
	echo -e "option,delimiter,\",\""
	echo "option,hasColumnNames,false"
	echo "option,quotedValues,true"
	echo "option,escapeQuotedValues,true"
}

function gen-import()
{
	pred=$1
	arity=$2

    file="${pred//:/-}.facts"

	echo -n "fromFile,\"facts/$file\""
	for i in $(seq $arity); do
		echo -n ",column:$i,$pred:$i"
	done
	echo ""

	echo -n "toPredicate,$pred"
	for i in $(seq $arity); do
		echo -n ",$pred:$i"
	done
	echo ""
}

function gen-imports()
{
	if test $1 = "-text"; then
		gen-text-options
	else
		gen-csv-options
	fi

	# entities
	gen-import PrimitiveType 1
	gen-import ClassType 1
	gen-import ArrayType 1
	gen-import InterfaceType 1
	gen-import NullType 1
	gen-import ComponentType 2

	# relations (TODO bring entities forward)
	gen-import StringConstant 1
    # gen-import ReifiedClass 2
	gen-import HeapAllocation:Type 2
	gen-import AssignHeapAllocation 3

	gen-import ActualParam 3
	gen-import AssignLocal 3
	gen-import AssignCast 4
	gen-import AssignReturnValue 2
	gen-import DirectSuperinterface 2
	gen-import DirectSuperclass 2
	gen-import FieldSignature 4
	gen-import FieldModifier 2
	gen-import FormalParam 3
	gen-import LoadInstanceField 4
	gen-import LoadArrayIndex 3
	gen-import LoadStaticField 3
	gen-import LoadPrimStaticField 2

	gen-import MethodDeclaration 2
	gen-import MethodDeclaration:Exception 2
	gen-import MethodModifier 2
	gen-import MethodSignature:SimpleName 2
	gen-import MethodSignature:Descriptor 2
	gen-import MethodSignature:Type 2

	gen-import ReturnVar 2

	gen-import SpecialMethodInvocation:Base 2
	gen-import SpecialMethodInvocation:Signature 2
	gen-import SpecialMethodInvocation:In 2

	gen-import VirtualMethodInvocation:Base 2
	gen-import VirtualMethodInvocation:Signature 2
	gen-import VirtualMethodInvocation:In 2
	gen-import VirtualMethodInvocation 3 # TODO eliminate

	gen-import StaticMethodInvocation 3 # TODO eliminate
	gen-import StaticMethodInvocation:In 2
	gen-import StaticMethodInvocation:Signature 2

	gen-import StoreInstanceField 4
	gen-import StoreArrayIndex 3
	gen-import StoreStaticField 3
	gen-import StorePrimStaticField 2

	gen-import Var:Type 2
	gen-import Var:DeclaringMethod 2

	gen-import ApplicationClass 1

	gen-import ThisVar 2
	gen-import Throw 2
	gen-import Throw:Method 2

	gen-import SimpleExceptionHandler 3
	gen-import ExceptionHandler:Method 2
	gen-import ExceptionHandler:Type 2
	gen-import ExceptionHandler:FormalParam 2
	gen-import ExceptionHandler:Begin 2
	gen-import ExceptionHandler:End 2
	gen-import ExceptionHandler:Previous 2

	gen-import Instruction:Index 2
    gen-import Properties 3

#gen-import ClassConstant 1
#gen-import ExceptionHandlerRef 1
#gen-import FieldSignatureRef 1
#gen-import MethodDescriptorRef 1
#gen-import MethodInvocationRef 1
#gen-import MethodSignatureRef 1
#gen-import ModifierRef 1
##gen-import NormalHeapAllocationRef 1
#gen-import SimpleNameRef 1
#gen-import ThrowRef 1
#gen-import VarRef 1
}

function main()
{
	gen-imports $1 > $2
}

main $1 $2
