#ifndef BOUND_VAR_POINTS_TO
#define BOUND_VAR_POINTS_TO(hctx, value, ctx, var) VarPointsTo(hctx, value, ctx, var) 
#endif

#ifndef BOUND_INSTANCE_FIELD_POINTS_TO
#define BOUND_INSTANCE_FIELD_POINTS_TO(hctx, value, sig, basehctx, basevalue) InstanceFieldPointsTo(hctx, value, sig, basehctx, basevalue)
#endif

#include "main.dl"
#include "basic-context-sensitivity.dl"

.init mainAnalysis = BasicContextSensitivity<CONFIGURATION>
