// Extra logic included by some tests.

.output mainAnalysis.ArrayIndexPointsTo
.output mainAnalysis.InstanceFieldPointsTo
.output mainAnalysis.StaticFieldPointsTo
.output mainAnalysis.VarPointsTo
.output mainAnalysis.MethodHandleCallGraphEdge
.output mainAnalysis.LambdaObject
.output mainAnalysis.LambdaCallGraphEdge

#ifdef REFLECTION_DYNAMIC_PROXIES
.output mainAnalysis.ProxyCallGraphEdge
#endif // REFLECTION_DYNAMIC_PROXIES

#define varPointsTo(v, h) mainAnalysis.VarPointsTo(_, h, _, v)
#define methodHandleCGE(i, m) mainAnalysis.MethodHandleCallGraphEdge(_, i, _, m, _, _)
#define reachable(m) mainAnalysis.Reachable(m)
