#include "test-exports.dl"

.decl TestId(?id:symbol)
.output TestId

TestId("test1.1") :-
  varPointsTo("<Main: void main(java.lang.String[])>/cA#_31", "<class A>").
TestId("test1.2") :-
  varPointsTo("<Main: void main(java.lang.String[])>/cA_2#_39", "<class A>").
TestId("test1.3") :-
  varPointsTo("<Main: void main(java.lang.String[])>/constr#_32", "<<reified constructor <A: void <init>()>>>").
TestId("test1.4") :-
  varPointsTo("<Main: void main(java.lang.String[])>/constr2#_42", "<<reified constructor <A: void <init>(java.lang.Integer,B)>>>").
TestId("test1.5") :-
  varPointsTo("<Main: void main(java.lang.String[])>/a3#_33", "<reflective Class.newInstance/new A>").
TestId("test1.6") :-
  varPointsTo("<Main: void main(java.lang.String[])>/a3_2#_35", "<reflective Constructor.newInstance/new A>").
TestId("test1.7") :-
  varPointsTo("<Main: void main(java.lang.String[])>/iField#_46", "<<reified field <A: java.lang.Integer i>>>").
TestId("test1.8") :-
  varPointsTo("<Main: void main(java.lang.String[])>/bFieldVal#_52", "<A: void <init>()>/new B/0").
TestId("test1.9") :-
  varPointsTo("<Main: void main(java.lang.String[])>/bFieldValB#_53", "<A: void <init>()>/new B/0").
TestId("test1.10") :-
  varPointsTo("<Main: void testProxies()>/g#_109", "<proxy object for interface G at <Main: void testProxies()>/java.lang.reflect.Proxy.newProxyInstance/0>").

#ifdef REFLECTION_DYNAMIC_PROXIES
TestId("test1.11") :-
  proxyCGE("<Main: void testProxies()>/G.countInteger/0", "<DHandler: java.lang.Object invoke(java.lang.Object,java.lang.reflect.Method,java.lang.Object[])>").
#endif // REFLECTION_DYNAMIC_PROXIES
