// Extra logic included by some tests.

.output mainAnalysis.ArrayIndexPointsTo
.output mainAnalysis.InstanceFieldPointsTo
.output mainAnalysis.StaticFieldPointsTo
.output mainAnalysis.VarPointsTo
.output mainAnalysis.MethodHandleCallGraphEdge
.output mainAnalysis.LambdaCallSite
.output mainAnalysis.LambdaCallGraphEdge

#ifdef REFLECTION_DYNAMIC_PROXIES
.output mainAnalysis.ProxyCallGraphEdge
#endif // REFLECTION_DYNAMIC_PROXIES
