// Context-insensitive pointer analysis with on-the-fly call graph discovery

// This analysis has no context for either method calls or heap objects.
// This is emulated by creating a single Context object and a single HContext
// object, which are used everywhere.
.decl ContextFromRealContext(?ctx:Context)

.decl HContextFromRealHContext(?hctx:HContext)

/**
 * Reachable methods. Main method, for sure.
 */
Reachable(?method) :-
   MainMethodDeclaration(?method).