// The rules below generate the metadata that drive SARIF generation.

// Populate this relation to add SARIF output for relations. Each
// tuple contains the following fields:
// name              : the name of the relation output (<name>.csv)
// doopIdPosition    : the index of the column containing the target element
//                     (given by a Doop id)
// contentType       : the type of element described by the Doop id (examples:
//                     Method, Field, MethodInvocation)
// resultMessage     : the message to show on each element appearance -- this can
//                     contain binding placeholders, e.g. "@@1" is the contents of
//                     column 1 (zero-based) in the relation for the same Doop id
// ruleDescription   : the description of the general rule corresponding to the relation
.decl SARIF_InterestingRelation(?name:symbol, ?doopIdPosition:number, ?contentType:symbol, ?resultMessage:symbol, ?ruleDescription:symbol)
.output SARIF_InterestingRelation

.output PhantomType
SARIF_InterestingRelation("PhantomType", 0, "Class", "Type is phantom.", "Type is phantom, this could be an indication of missing code.").
.output mainAnalysis.PhantomInvoke(IO="file",filename="PhantomInvoke.csv",delimiter="\t")
SARIF_InterestingRelation("PhantomInvoke", 0, "MethodInvocation", "Invoked method is phantom.", "Invoked method is phantom, this could be an indication of missing code.").

#ifdef GENERATE_OPTIMIZATION_DIRECTIVES
SARIF_InterestingRelation("MethodToRemove", 0, "Method", "Method seems to be unused and can be removed.", "Method seems to be unused and can be removed.").
SARIF_InterestingRelation("SingleInvocationToInline", 0, "MethodInvocation", "Invoked method can be inlined: @@1", "Invoked method can be inlined.").
#endif // GENERATE_OPTIMIZATION_DIRECTIVES

#ifdef INFORMATION_FLOW
.output AppTaintedVarPointsTo
SARIF_InterestingRelation("AppTaintedVarPointsTo", 1, "Variable", "Variable is tainted, points to @@0.", "Variable is tainted.").
#endif // INFORMATION_FLOW

#ifdef X_SERVER_LOGIC
SARIF_InterestingRelation("Server_Field_ShadowedBy", 0, "Field", "Field is shadowed by field @@1", "Field is shadowed.").
#endif // X_SERVER_LOGIC
