.output VarPointsTo
.output InstanceFieldPointsTo
.output isFunctionObjectAllocation
.output Reachable

.output ResolvedActualParamValue
.output FunctionInvResolvesTo
.output isClassObjectAllocation
.output GlobalNamePointsTo
.output isClassInstanceAllocation
.output ClassInstanceAllocationInitializingClassObject

.output ReachableContext
.output CallGraphEdge

#ifndef X_STATS_NONE
.output Stats_Metrics(IO="file",filename="Stats_Metrics.csv",delimiter="\t")
#endif // X_STATS_NONE