#!/bin/bash

if [ "$#" = 0 ] ; then set -- " " ; fi

src=$(pwd)
cd ../../

while (( "$#" )); do
	out="$(cat $src/$1 | java org.antlr.v4.gui.TestRig doop.dsl.Datalog program 2>&1)"

	echo '--------------------'
	if [ "X$out" = 'X' ] ; then
		echo $'\e[33m'"$1 "$'\e[0;32mOK\e[0m'
	else
		echo "$out"
		echo $'\e[33m'"$1 "$'\e[0;31mFAIL\e[0m'
	fi

	shift
done
