#!/bin/bash

test "$#" = 0 && { echo "No arguments!" ; exit 1 ; }

src=$(pwd)
cd ../../

while (( "$#" )); do
	test ${1##*.} = 'logic' && grammar=datalog.Datalog || grammar=script.Script
	out="$(cat $src/$1 | java org.antlr.v4.gui.TestRig doop.dsl.$grammar program 2>&1)"

	echo '--------------------'
	if [ "X$out" = 'X' ] ; then
		echo $'\e[33m'"$1 "$'\e[0;32mOK\e[0m'
	else
		echo "$out"
		echo $'\e[33m'"$1 "$'\e[0;31mFAIL\e[0m'
	fi

	shift
done
