// Context-sensitive pointer analysis with context of 1 object and a
// context-sensitive heap abstraction.

// In this analysis, the real context is a pair of Values and the real
// heap context a single Value. Keeping mapping functions is the way
// to handle analyses where HContext = Context (since the language considers
// them different types).
.type Context = [ value1:Value, value2:Value ]
.type HContext = [ value:Value ]