#include "../souffle-logic/facts/flow-sensitive-schema.dl"
#include "../souffle-logic/facts/flow-insensitive-schema.dl"
#include "../souffle-logic/facts/to-flow-sensitive.dl"
#include "../souffle-logic/facts/import-entities.dl"
#include "../souffle-logic/facts/import-facts.dl"
#include "../souffle-logic/basic/type-hierarchy.dl"
#include "../souffle-logic/basic/method-lookup.dl"

.output SupertypeOf
.output MethodLookup

.decl Invocation_Parts(?invocation:MethodInvocation, ?simplename:symbol, ?descriptor:symbol, ?basetype:Type)
.output Invocation_Parts

Invocation_Parts(?invocation, ?simplename, ?descriptor, ?basetype) :-
    VirtualMethodInvocation_SimpleName(?invocation, ?simplename),
    VirtualMethodInvocation_Descriptor(?invocation, ?descriptor),
    VirtualMethodInvocation_Base(?invocation, ?base),
    Var_Type(?base, ?basetype).
